version: '3'
services:
  consultas:
    image: node:lts-alpine
    working_dir: /usr/src/consultas
    restart: unless-stopped
    command: sh -c "npm install && npm run build && npm start"
    volumes:
      - ./:/usr/src/consultas/
    ports: 
      - 3000:3000
